# Generated by Django 2.2.20 on 2021-06-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_title', models.TextField()),
                ('mission_instructions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
